$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:false,
    responsive:{
        0:{
            items:1.5
        },
        600:{
            items:3.5
        },
        1000:{
            items:5.5
        }
    }
})